CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  credit INTEGER NOT NULL DEFAULT 0,
  admin BOOLEAN NOT NULL DEFAULT FALSE,
  pterodatyl BOOLEAN NOT NULL DEFAULT FALSE,
  create_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
